-- Generated by `supabase db diff` from
-- supabase/schemas/02_functions/02-04_rcp_functions.sql, then trimmed per
-- CLAUDE.md: the ~144 `revoke ... from anon|authenticated|service_role` lines
-- are the usual default-privilege artifact, and `get_authorized_orgs` /
-- `hash_api_key` were re-emitted unchanged (CRLF in the schema files vs LF in
-- the database), so none of them belong here.
--
-- The revoke/grant at the bottom is hand-written on purpose: migra does not
-- emit function privileges, so `db diff` drops them silently. Without it
-- `create function`'s default would leave this callable by public.
--
-- Why the function exists at all: the update policy on contacts_addresses
-- defers to public.contact_address_update_rules, which requires the incoming
-- `status` and `extra` to equal the stored ones — freezing both, so a member
-- may only change which contact an address belongs to. Blocking needs to write
-- `status`, and this is the narrow, audited way to allow exactly that.

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.set_contact_address_blocked(p_address text, p_service public.service, p_blocked boolean DEFAULT true)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  update public.contacts_addresses
  set status = case when p_blocked then 'blocked' else 'active' end
  where address = p_address
    and service = p_service
    and organization_id in (select public.get_authorized_orgs('member'));

  -- A missing row and an unauthorised one answer the same way on purpose:
  -- confirming that an address exists inside an organization the caller cannot
  -- read would leak what the select policy is there to hide.
  if not found then
    raise exception 'contact address not found or not authorized'
      using errcode = 'insufficient_privilege';
  end if;
end;
$function$
;

revoke execute on function
  public.set_contact_address_blocked(text, public.service, boolean)
from public;

grant execute on function
  public.set_contact_address_blocked(text, public.service, boolean)
to anon, authenticated, service_role;
