-- Issue #10 [SECURITY] Store API keys hashed.
--
-- public.api_keys.key held the secret verbatim: readable by any owner of the
-- org through RLS, and by anyone holding a dump, a backup or a replica. From
-- here on only sha256(key) is persisted; the plaintext is returned once, by
-- public.create_api_key(), and is not recoverable afterwards.
--
-- Existing keys are NOT migrated — a hash cannot be derived from a column we
-- are dropping, and it is the clients that hold the plaintext. No customer uses
-- API keys yet, so every existing key is deleted, i.e. invalidated. Issue new
-- ones with create_api_key().
--
-- Hand-written rather than generated by `supabase db diff` (which is blocked
-- locally, see the db-reset issues) and because it carries a DML step that
-- diff would not emit. The declarative files under supabase/schemas/ are edited
-- in the same change, so the next successful diff must come out empty.

-- get_authorized_orgs backs every RLS policy in the schema; replacing it takes
-- a lock that concurrent requests wait on. Fail fast instead of piling up
-- behind a long transaction during automatic deploy.
set local lock_timeout = '5s';

-- 1. The canonical hash, shared by the RLS policy, get_authorized_orgs and
--    create_api_key so the three cannot drift apart. Built-ins only
--    (sha256/convert_to/encode are in pg_catalog): no pgcrypto dependency and
--    nothing to schema-qualify under `search_path = ''`.
--    strict: a missing `api-key` header hashes to null, matching no row.
create function public.hash_api_key(p_key text) returns text
language sql
immutable
strict
parallel safe
set search_path to ''
as $$
  select encode(sha256(convert_to(p_key, 'UTF8')), 'hex');
$$;

-- 2. Invalidate every existing key: the plaintext is about to become
--    unverifiable.
delete from public.api_keys;

-- 3. Swap the column. The SELECT policy references api_keys.key, so it has to
--    go first; the INSERT policy is dropped for good (see step 5).
drop policy "owners can read their orgs api keys" on public.api_keys;
drop policy "owners can create their orgs api keys" on public.api_keys;

alter table public.api_keys drop constraint api_keys_key_key;
alter table public.api_keys drop column key;

alter table public.api_keys add column key_hash text not null;

alter table only public.api_keys
add constraint api_keys_key_hash_key
unique (key_hash);

-- 4. Same self-read rule as before, now over the hash.
create policy "owners can read their orgs api keys"
on public.api_keys
for select
to authenticated, anon
using (
  key_hash = public.hash_api_key(
    current_setting('request.headers', true)::json->>'api-key'
  )
  or organization_id in (
    select public.get_authorized_orgs('owner')
  )
);

-- 5. No INSERT policy is recreated on purpose: keys are minted by
--    create_api_key() below, the only place that generates the secret and
--    stores its hash. A direct INSERT would let the client choose the stored
--    value.
create function public.create_api_key(
  p_organization_id uuid,
  p_name text,
  p_role public.role default 'member'
) returns table (api_key_id uuid, api_key text)
language plpgsql
security definer
set search_path to ''
as $$
declare
  _key text;
  _id uuid;
begin
  if p_organization_id is null or coalesce(trim(p_name), '') = '' then
    raise exception using
      errcode = '22023',
      message = 'organization_id and name are required';
  end if;

  -- Only an owner of the target org may mint keys. get_authorized_orgs returns
  -- the empty set (it deliberately does not raise) when the caller lacks the
  -- role, so the check has to be explicit here.
  if not exists (
    select 1 from public.get_authorized_orgs('owner') as authorized(org_id)
    where authorized.org_id = p_organization_id
  ) then
    raise exception using
      errcode = '42501',
      message = 'insufficient permissions, owner role required';
  end if;

  -- 244 bits from pg_strong_random (gen_random_uuid is a v4 UUID). Built-in, so
  -- this does not pull in pgcrypto's gen_random_bytes.
  _key := 'obsp_' ||
    replace(gen_random_uuid()::text, '-', '') ||
    replace(gen_random_uuid()::text, '-', '');

  insert into public.api_keys (organization_id, name, role, key_hash)
  values (p_organization_id, trim(p_name), p_role, public.hash_api_key(_key))
  returning id into _id;

  -- The only moment the plaintext key leaves the database.
  return query select _id, _key;
end;
$$;

-- `create function` grants execute to `public` by default, and Supabase's
-- default privileges add anon/authenticated/service_role on top; spell the ACL
-- out so it does not depend on either (same treatment as the vault accessors in
-- 02-05_vault_secrets.sql). The owner check above is the real boundary.
-- service_role is revoked because it cannot use this function anyway: it sends
-- neither a JWT nor an `api-key` header, so get_authorized_orgs raises.
revoke execute on function
  public.create_api_key(uuid, text, public.role)
from public, service_role;

grant execute on function public.create_api_key(uuid, text, public.role)
to anon, authenticated;

-- hash_api_key keeps the default `public` grant: the api_keys SELECT policy
-- calls it, and policy expressions run with the invoking role's privileges, so
-- revoking it from anon/authenticated would break the self-read path. It leaks
-- nothing — sha256 of a value the caller already holds.

-- 6. Authenticate the `api-key` header by hash.
create or replace function public.get_authorized_orgs(role public.role default 'member') returns setof uuid
language plpgsql
security definer
set search_path to ''
as $$
declare
  req_level int;
  api_key text;
  org_id uuid;
begin
  req_level := case role::text
    when 'owner' then 3
    when 'admin' then 2
    else 1 -- 'member'
  end;

  -- First, try JWT authentication via auth.uid()
  if auth.uid() is not null then
    return query select organization_id from public.agents
    where
      user_id = auth.uid()
    and (
      extra->'invitation' is null
      or extra->'invitation'->>'status' = 'accepted'
    )
    and (
      case (extra->>'role')
        when 'owner' then 3
        when 'admin' then 2
        else 1 -- 'member'
      end
    ) >= req_level;

    -- Authenticated but lacking the requested role: return the empty set so RLS
    -- subqueries can fall through to other OR-combined policies (e.g. a member
    -- accepting their own invitation while an owner-only policy is also evaluated).
    -- Raising here would short-circuit the whole RLS evaluation.
    -- raise exception using
    --   errcode = '42501',
    --   message = format('insufficient permissions, %s role required', role::text);
    return;
  end if;

  -- Fallback to API key authentication
  api_key := current_setting('request.headers', true)::json->>'api-key';

  if api_key is not null then
    select a.organization_id into org_id
    from public.api_keys a
    where a.key_hash = public.hash_api_key(api_key)
    and (
      case (a.role::text)
        when 'owner' then 3
        when 'admin' then 2
        else 1 -- 'member'
      end
    ) >= req_level;

    if org_id is not null then
      return next org_id;
    end if;
    -- Same reasoning as the JWT branch: invalid key or insufficient role returns
    -- the empty set, not a raise. Validate api-key existence at the request edge
    -- (e.g. a pre-request hook) if you want loud failure for missing/invalid keys.
    -- raise exception using
    --   errcode = '42501',
    --   message = format('invalid api key or insufficient permissions, %s role required', role::text);
    return;
  end if;

  raise exception using
    errcode = '42501',
    message = 'authentication required',
    hint = 'use api-key header or jwt authentication';
end;
$$;
